// server constants
export default {
  DEFAULT_PLAYER_ATTACK_SPEED: 15,
  DEFAULT_PLAYER_VELOCITY: 3,
  RANGER_PROJECTILE_RANGE: 300,
  DEFAULT_PROJECTILE_SPEED: 12,
  DEFAULT_PROJECTILE_TO_USER_OFFSET: 12,
  FRAMES_PER_SECOND: 60,
  DEFAULT_PLAYER_MAXIMUM_HEALTH: 100,
  DEFAULT_CIRCLE_RADIUS: 10,
  DEFAULT_DAMAGE_FROM_PROJECTILE: 10,
  DEFAULT_STARTING_STOCK: 2,
  DEFAULT_LAST_CAST_FRAME: -1000000,
}
