export default {
  DEFAULT_MAP_VIEW_WIDTH: 1024,
  DEFAULT_MAP_VIEW_HEIGHT: 512,
  DEFAULT_PLAYER_ATTACK_SPEED: 0.25,
  DEFAULT_PLAYER_VELOCITY: 3,
  DEFAULT_PROJECTILE_RANGE: 300,
  DEFAULT_PROJECTILE_SPEED: 12,
  DEFAULT_PROJECTILE_TO_USER_OFFSET: 12,
  FRAMES_PER_SECOND: 60,
  DEFAULT_PLAYER_MAXIMUM_HEALTH: 100,
}
