export default {
  DEFAULT_MAP_VIEW_WIDTH: 1024,
  DEFAULT_MAP_VIEW_HEIGHT: 512,
  DEFAULT_ROWS: 18,
  DEFAULT_COLUMNS: 26,
  DEFAULT_TILE_SIZE: 64,
  DEFAULT_MAP_WIDTH: 26 * 64,
  DEFAULT_MAP_HEIGHT: 18 * 64,
}