apiVersion: v1
kind: Service
metadata:
  name: play-moba
spec:
  type: LoadBalancer
  selector:
    agones.dev/role: gameserver
  ports:
    - name: http
      protocol: TCP
      port: 3000
      targetPort: 3000
