export default {
  client: {
    JOIN_GAME: "JOIN_GAME",
    USER_MOUSE_CLICK: "USER_MOUSE_CLICK",
    USER_CAST: "USER_CAST",
  },
  server: {
    END_GAME: "END_GAME",
    UPDATE_GAME_STATE: "UPDATE_GAME_STATE",
    RECEIVED_DAMAGE: "RECEIVED_DAMAGE",
    CASTING: "CASTING"
  }
}