name: Deploy Azure

on:  
  schedule:
    - cron: '0 10 * * *'  # every day at 10:00 UTC
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: "Login via Azure CLI"
        uses: azure/login@v1.1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}
      - name: "Docker Login"
        uses: azure/docker-login@v1
        with:
          login-server: playmoba.azurecr.io
          username: ${{ secrets.ACR_USERNAME }}
          password: ${{ secrets.ACR_PASSWORD }}
      - name: "Delete Containers"
        run: |
          az acr repository delete -n playmoba --repository game-server --yes
      - name: "Build Docker Container"
        run: |
          npm install
          npm run build-prod
          docker build -t playmoba.azurecr.io/game-server .
          docker push playmoba.azurecr.io/game-server
      - name: "Fetch AKS Credentials"
        run: |
          az aks get-credentials --resource-group play-moba --name play-moba
          kubectl config use-context play-moba
      - name: "Update Kubernetes Controllers"
        run: |
          kubectl delete fleet --all
          kubectl apply -f kubeConfig/aks/fleet.yaml
          kubectl apply -f kubeConfig/aks/autoscaler.yaml
          kubectl apply -f kubeConfig/service.yaml
